# Generated by Django 5.1.6 on 2026-08-11 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusKuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="berlaku untuk tanggal",
                    ),
                ),
                ("jumlah", models.PositiveSmallIntegerField(verbose_name="tambahan panggilan")),
                ("alasan", models.CharField(blank=True, max_length=200, verbose_name="alasan")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="waktu")),
                (
                    "diberikan_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_diberikan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="diberikan oleh",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_kuota",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "bonus kuota",
                "verbose_name_plural": "bonus kuota",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="panel_bonus_user_id_1301de_idx")
                ],
            },
        ),
    ]
