# Generated by Django 5.1.6 on 2026-07-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nama menu")),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="biaya bahan"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="harga jual"
                    ),
                ),
                (
                    "weekly_sales",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="terjual per minggu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREEN", "pertahankan"),
                            ("YELLOW", "perbaiki harga"),
                            ("RED", "perlu ditinjau"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="terakhir diubah")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="dibuat")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pemilik",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu tersimpan",
                "verbose_name_plural": "menu tersimpan",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "name"), name="menu_unik_per_user")
                ],
            },
        ),
    ]
