# Generated by Django 5.1.6 on 2026-07-27 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="affiliate.id", max_length=50, verbose_name="penyedia"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=120, unique=True, verbose_name="id dari penyedia"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="isi kiriman")),
                (
                    "signature_valid",
                    models.BooleanField(default=False, verbose_name="tanda tangan sah"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="waktu diproses"),
                ),
                ("error", models.TextField(blank=True, verbose_name="catatan galat")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="diterima")),
            ],
            options={
                "verbose_name": "kiriman webhook",
                "verbose_name_plural": "kiriman webhook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="kunci lisensi")),
                ("plan", models.CharField(default="lifetime", max_length=30, verbose_name="paket")),
                (
                    "order_id",
                    models.CharField(max_length=120, unique=True, verbose_name="nomor pesanan"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="nilai bayar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "menunggu"),
                            ("active", "aktif"),
                            ("revoked", "dicabut"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="waktu aktivasi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="dibuat")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pemilik",
                    ),
                ),
            ],
            options={
                "verbose_name": "lisensi",
                "verbose_name_plural": "lisensi",
                "ordering": ["-created_at"],
            },
        ),
    ]
