# Generated by Django 5.1.6 on 2026-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_webhookevent_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kredensial_terkirim_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="kredensial terkirim"),
        ),
    ]
