# Generated by Django 5.1.6 on 2026-07-27 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="tanggal"
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="jumlah panggilan")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quotas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "kuota harian",
                "verbose_name_plural": "kuota harian",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="kuota_unik_per_user_per_hari"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.CharField(max_length=60, verbose_name="endpoint")),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "berhasil"), ("error", "gagal")],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(default=0, verbose_name="lama proses (ms)"),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="jumlah pengulangan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="waktu"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "catatan pemakaian",
                "verbose_name_plural": "catatan pemakaian",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="usage_usage_user_id_3c098f_idx"
                    )
                ],
            },
        ),
    ]
