# Generated by Django 5.1.6 on 2026-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagelog",
            name="output_tokens",
            field=models.PositiveIntegerField(default=0, verbose_name="token keluar"),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="prompt_tokens",
            field=models.PositiveIntegerField(default=0, verbose_name="token masuk"),
        ),
    ]
