# Generated by Django 5.1.6 on 2026-08-11 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0002_usagelog_output_tokens_usagelog_prompt_tokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usagelog",
            options={
                "ordering": ["-created_at"],
                "permissions": [("bypass_quota", "Boleh memakai AI tanpa batas kuota")],
                "verbose_name": "catatan pemakaian",
                "verbose_name_plural": "catatan pemakaian",
            },
        ),
    ]
